version: '3'

services:
  stackcoin:
    image: jackharrhy/stackcoin
    build: ./.
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    volumes:
      - ./data/stackcoin.db:/app/data/stackcoin.db
