version: '3.7'

services:
  stackcoin:
    image: stackcoin
    environment:
      - STACKCOIN_DISCORD_TOKEN=
      - STACKCOIN_DISCORD_CLIENT_ID=
      - STACKCOIN_REDIS_HOST=redis
      - STACKCOIN_DATABASE_URL=
      - STACKCOIN_PREFIX=
      - STACKCOIN_TEST_GUILD_SNOWFLAKE=
    ports:
      - "3000:3000"
    volumes:
      - ./data/stackcoin.db:/app/data/stackcoin.db
    networks:
      - redis
    depends_on:
      - redis

  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis
    volumes:
      - stackcoin_redis_data:/data

networks:
  redis:

volumes:
  stackcoin_redis_data:
