version: '3.7'

services:
  stackcoin:
    image: stackcoin
    environment:
      - STACKCOIN_DISCORD_TOKEN=
      - STACKCOIN_DISCORD_CLIENT_ID=
    ports:
      - "3000:3000"
  redis:
    image: redis:5-alpine
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - stackcoin_redis_data:/data

volumes:
  stackcoin_redis_data:
    external: true