name: Crystal Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Deps.
        run: shards install

      - name: Build docs
        run: crystal docs

      - name: Deploy docs
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: gh-pages
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
